### ISSUE TITLE
1.20.6: Key ``Scan.Item_Use`` not working.

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/Protect#10]
## Steps to reproduce your problem.
1) Install Protect
2) Add this to ``Scan.Item_Use`` in settings
```yml
  - '*_PICKAXE'
  - '*_AXE'
  - '*_SHOVEL'
  - '*_SWORD'
  - '*_HOE'
```
3) Type ``/protect reload``
4) Type ``/minecraft:give @s diamond_pickaxe``
5) Type ``/protect edititem enchant DIG_SPEED 100`` (while holding the diamond pickaxe)
6) Right click and left click
7) Nothing happens...

## Expected behaviour:
The plugin will remove the item due to it having an efficiency level of 100 but it doesn't

## Debug file:
https://file.io/o84Rw3ZQu3ZW

**Comment by TheIntolerant** [comment]
It is worth noting that this key does however work for the items in the default file but other items that are added seem not to work!

**Comment by kangarko** [comment]
Thanks, sorry for inactivity, I see this but I will get to this after foundation 7 and chatcontrol 11 are out.

**Comment by kangarko** [comment]
Thanks, I finally fixed it! :)
