### ISSUE TITLE
Minecraft Version: Issue Title Paper 1.21.1-56: NullPointException error

### ISSUE THREAD

**Issue by ChiefWarPig** [kangarko/Protect#13]
I haven't been well enough to set this plugin up until this week and I am struggling to get the rules to work as expected. I commented the rules out initially as I haven't been well enough and it was confiscating Items I didn't want it to. I am now starting to uncomment and try and set the rules up to work with my server setup. It appears that it does not remove Hex colour codes when checking the name length rule as a result I have tried to implement an ignore tag rule and tried both these options as a tag to check against "executableitems:ei-id" & "executrableitems". This should I believe looking at the wiki make the plugin ignore long names from items I have made in the Executable Items plugin, unfortunately this is not the case, not sure if this part of the error is user error on my part or related to the other issue I am having? 
The other issue I am having is that when items are being confiscated under this rule for item name length there does not appear to be a log being made and so I can not see what a palyer has had confiscated without trawling through pages of console logs. Other items from other rules as you can see do seem to be getting logged. 
I have attached screeen shots of the logs in game and the NBT data I am trying to check against to prevent these items being removed. Thank you in advanced for any assistance you can provide. 
![Screenshot 2024-09-06 104532](https://github.com/user-attachments/assets/27cb7d5d-a6c8-4d78-b4a3-1412c7b6fb9d)
![Screenshot 2024-09-06 111231](https://github.com/user-attachments/assets/9d6a54bf-a1b1-4586-8a9f-f90d87d2dcfc)
![Screenshot 2024-09-06 111332](https://github.com/user-attachments/assets/a499f478-8caf-4963-974c-41bcc921dcf6)

Reproduce: 
Have an item in the inventory that exceeds the config name length (Item name length without colour codes is 16 characters including 1 space in the name. Name being used is using Hex colours "#2400d6C#3410c8h#4320bar#5330ado#62409fn#725091i#816083c#917076l#a07f68e#b08f5as
  #bf9f4cS#cfaf3ew#debf31o#eecf23r#fddf15d"
  
  Console Log link: https://mclo.gs/B2nL2oF
Protectect Log: 
[error(3).log](https://github.com/user-attachments/files/16906578/error.3.log)
/protect debug output: https://ufile.io/mcb808t9

**Comment by kangarko** [comment]
Thanks, will be addressed a bit later, we're reworking our library powering Protect first.

**Comment by ChiefWarPig** [comment]
Ok so I wasn't doing anything wrong with the rules?

**Comment by kangarko** [comment]
Sorry for the delay, I could not push an update because Protect relies on a library which we were rewriting.

Your sword with the long name should no longer be taken, I made the colors being ignored when comparing the length.

Also, I got it to show up in "/protect logs items":

![a](https://i.imgur.com/Bt8KWXf.png)
