### ISSUE TITLE
minecraft 1.21

### ISSUE THREAD

**Issue by elhadesgamer97** [kangarko/Protect#16]
I have a question baout plugin PROTECT, how do I disable deleting items that have lore or RGB names? I set it and it instantly deleted the players' items, it practically screwed everything up for me. Is there a way to only avoid glitches or dupes and not delete custom-created items with lores, RGB names, their food stacks, golden apples?

**Comment by kangarko** [comment]
Hey!

I am sorry for the wrong confiscation.

Can you send a screenshot of the items that should be excluded? I need to get an idea and will make the exclusion for you, thanks.

**Comment by elhadesgamer97** [comment]
![1](https://github.com/user-attachments/assets/f7e05302-f270-49c7-87a8-90bf768bc2aa)
![2](https://github.com/user-attachments/assets/c14cb3af-0cff-4ddb-a0c9-0d0d4c7375d7)
![3](https://github.com/user-attachments/assets/15957712-38e8-4213-88a6-a81625eb5e30)
![4](https://github.com/user-attachments/assets/d04bd489-7d16-40c5-8859-7375c46610c6)

**Comment by kangarko** [comment]
Working on it! Will be back in office by monday so I expect to push a fix by mon or tuesday :)

**Comment by elhadesgamer97** [comment]
Thanks, I hope this is solved or fixed :3

**Comment by kangarko** [comment]
In the next version, I will add the Ignore.Custom_Display_Name and Ignore.Custom_Lore options, which, if enabled, will ignore all of your custom items. Please see the warning in the comments of that key for a note.


I also added “ignore enchantlevel <level>” operator to ignore the scan if the item has only enchants less or equal the given level. Useful if your custom plugin gives enchants higher than vanilla which you can use for the items on the image you sent.

**Comment by elhadesgamer97** [comment]
In the next version, I will add the Ignore.Custom_Display_Name and Ignore.Custom_Lore options, which, if enabled, will ignore all of your custom items. Please see the warning in the comments of that key for a note.

I also added “ignore enchantlevel ” operator to ignore the scan if the item has only enchants less or equal the given level. Useful if your custom plugin gives enchants higher than vanilla which you can use for the items on the image you sent.

**Comment by kangarko** [comment]
Can't see your response all I see is you quoted me verbatim

**Comment by elhadesgamer97** [comment]
![image](https://github.com/user-attachments/assets/0f6b894a-e78a-48f9-acaf-86fc0b874c08)

**Comment by kangarko** [comment]
Still only seeing my own text

**Comment by elhadesgamer97** [comment]
> Still only seeing my own text

In the next version, I will add the Ignore.Custom_Display_Name and Ignore.Custom_Lore options, which, if enabled, will ignore all of your custom items. Please see the warning in the comments of that key for a note.

I also added “ignore enchantlevel ” operator to ignore the scan if the item has only enchants less or equal the given level. Useful if your custom plugin gives enchants higher than vanilla which you can use for the items on the image you sent.
now?

**Comment by kangarko** [comment]
No. Here is what I see:

![a](https://i.imgur.com/0Z4hQhr.png)

**Comment by elhadesgamer97** [comment]
When will the new project update come out?

**Comment by kangarko** [comment]
It already came out recently, can you try it?

**Comment by elhadesgamer97** [comment]
So far so good, Erp still removes or eliminates items with enchantments higher than those of vanilla, I don't know if there is a section to limit the maximum enchantment, for example in my SV the maximum is 12 regardless of the enchantment, so if there was a section that allows you to set that maximum enchantment level and if it exceeds it, it confiscates it.

**Comment by kangarko** [comment]
Have you placed the "ignore enchantlevel 12" operator for the rules that are causing the confiscation?

**Comment by elhadesgamer97** [comment]
I found it in the rules, but where do I put it?
since there is no option in settings

**Comment by kangarko** [comment]
Just put it into the rule like this:

```
match *
name enchant-too-high
ignore enchantlevel 12
check enchant too-high
then confiscate
```

**Comment by elhadesgamer97** [comment]
Ok, we have to add it as a rule, ok, thank you very much :3

**Comment by elhadesgamer97** [comment]
Hi, I still have problems with the confiscation of items, for some reason it takes them away from me and that's even though I raised the level, it adds the new conditions that you told me but still the confiscated ones, even items that are normal like enchanted apples.


-----------------------------------------------------------------------------
[Protect] Item confiscated.
[21:54:13 INFO]: [Protect] *--------- Rule match (enchant-not-applicable) from player join for hadesgamer97 --------- 
[21:54:13 INFO]: [Protect] MATCH: *
[21:54:13 INFO]: [Protect] CATCH: BOW
[21:54:13 INFO]: [Protect] Item confiscated.
[21:54:13 INFO]: [Protect] *--------- Rule match (enchant-not-applicable) from player join for hadesgamer97 --------- 
[21:54:13 INFO]: [Protect] MATCH: *
[21:54:13 INFO]: [Protect] CATCH: CROSSBOW
[21:54:13 INFO]: [Protect] Item confiscated.
[21:54:13 INFO]: [Protect] *--------- Rule match (enchant-not-applicable) from player join for hadesgamer97 --------- 
[21:54:13 INFO]: [Protect] MATCH: *
[21:54:13 INFO]: [Protect] CATCH: NETHERITE_AXE
[21:54:13 INFO]: [Protect] Item confiscated.
[21:54:13 INFO]: [Protect] *--------- Rule match (enchant-not-applicable) from player join for hadesgamer97 --------- 
[21:54:13 INFO]: [Protect] MATCH: *
[21:54:13 INFO]: [Protect] CATCH: MACE
[21:54:13 INFO]: [Protect] Item confiscated.

**Comment by kangarko** [comment]
I am sorry to hear, what enchants it's got? 

If not sure, can you please open /protect logs, get the confiscated item back and then run /protect iteminfo to see what enchants it's got?

**Comment by elhadesgamer97** [comment]
![protect](https://github.com/user-attachments/assets/759363cc-00c7-49e2-8d26-a3a52eaff091)

What I find strange is that even vanilla items are taken from me, it happens when I open a chest, for example golden apples or villager eggs, it confiscates them and I get the message that it was confiscated by: enchant-not-applicablet

**Comment by kangarko** [comment]
If vanilla golden apples or villager eggs are taken away that would be an alarming bug - I have tested this myself on 1.21.1 and they are not taken away: https://www.loom.com/share/5290215c5f4d42d6ba974c38d7a64214

Can you please try deleting the two enchant-related rules and copy the new default rules from below?

```
# -----------------------------------------------------------------------------------------------------
# Block enchants unapplicable to the given item.
# Use "ignore enchant <enchant>" to ignore enchants from custom plugins.
# See https://mineacademy.org/enchants for enchant names (works on ALL Minecraft versions).
# -----------------------------------------------------------------------------------------------------
match *
name enchant-not-applicable
# Ignore Boss eggs from the Boss plugin (mineacademy.org/boss)
ignore tag Boss_V4
check enchant not-applicable
then confiscate

# -----------------------------------------------------------------------------------------------------
# Block unnaturally high enchants.
# Use "ignore enchant <enchant>" to ignore enchants from custom plugins.
# Use "ignore enchantlevel <level>" to specify max level for enchants if you support higher than
# vanilla levels.
# See https://mineacademy.org/enchants for enchant names (works on ALL Minecraft versions).
# -----------------------------------------------------------------------------------------------------
match *
name enchant-too-high
check enchant too-high
then confiscate
```

Btw golden enchanted apples have another rule to cap their amount, you can remove the default rule "enchanted-apple" to stop that.

**Comment by elhadesgamer97** [comment]
![image](https://github.com/user-attachments/assets/107068e8-581a-4eef-a847-be1e52f3b476)
Ok I deleted and reloaded with the settings you told me before, but it still removes the armor, and it tells me it's because: enchantment not applicable, any way to ignore that, I think it's because some enchantment I put on the armor is not compatible or doesn't go with another enchantment, I don't know if that's the reason

![image](https://github.com/user-attachments/assets/780dcf83-9dcd-41b4-9958-f1a89c0e7955)
