### ISSUE TITLE
Minecraft Version: Error on Startup

### ISSUE THREAD

**Issue by Hyronymos1337** [kangarko/Protect#19]
](https://paste.twerion.net/cipabefuve.makefile)](https://paste.twerion.net/cipabefuve.makefile)

**Comment by Hyronymos1337** [comment]
https://paste.twerion.net/cipabefuve.makefile

**Comment by kangarko** [comment]
Hey! Sorry for the delay, please test the new version coming out tonight and re-post the error if it happens again, I did not experience any issues.

Also, please fix all the other problems in your error log since they can cause unwanted side effects.
