### ISSUE TITLE
Minecraft Version: Paper 1.21.1-132: java.lang.NullPointerException: Cannot read the array length because "this.armor" is null

### ISSUE THREAD

**Issue by ChiefWarPig** [kangarko/Protect#20]
Run the command /protect logs items and you get the above error message in console. 

[debug(4).zip](https://github.com/user-attachments/files/18052670/debug.4.zip)
Console Log also for reference. https://mclo.gs/cko98kx

**Comment by kangarko** [comment]
I apology, looks like my other commit had caused this: https://github.com/kangarko/Foundation/commit/07bdcf6e5f56111ebf44ea16464d6a8fdb4e8f2b. I now solved this issue and will ship a patch in the next version to reverse the wrong save.

**Comment by kangarko** [comment]
Correction, I can't find the "array length because "this.armor" is null" error anywhere in your log. Please repost on the next version if it happens again.

**Comment by ChiefWarPig** [comment]
Screen shot of the error for reference and thank you for the quick response. I will update you if the error is not resolve after the next version release. 
![Screenshot 2024-12-10 200236](https://github.com/user-attachments/assets/7f2ad647-71ef-45e1-9de2-4117ff8722e0)

**Comment by kangarko** [comment]
Ok gotcha. I see it in sentry too, thanks, fixing now.
