### ISSUE TITLE
1.21.1:  Logging TNT Crafting, Placement, and Ignition to In-Game and Discord Logs

### ISSUE THREAD

**Issue by developedbyalex** [kangarko/Protect#21]
Hi there,

I'm currently using Protect and would like to know if it's possible to log specific actions related to TNT in both in-game logs and Discord (via DiscordSRV or a similar integration). Here's what I'm aiming to achieve:

## Actions to Log:
1. **Crafting TNT**: Log when a player crafts TNT.
2. **Placing TNT**: Log when a player places TNT in the world.
3. **Lighting TNT**: Log when a player ignites TNT (using flint and steel or any other method).

## Desired Output:
- **In-Game Logs**: Send a log to the console or notify admins in-game.
- **Discord Logs**: Send a detailed message to a specific Discord channel, including:
  - Player name
  - World name
  - Coordinates
  - Any additional relevant details (e.g., playtime, gamemode, etc.).

**Comment by kangarko** [comment]
Hey! Thanks, that sounds great but unfortunately not. I recommend getting a logblock plugin instead.

**Comment by kangarko** [comment]
Regarding crafting a TNT I guess you can place that in the item use list in settings.yml and we will catch it in most cases.

**Comment by developedbyalex** [comment]
Thanks for the reply,

I tried implementing a few solutions to achieve TNT-related logging, but it seems to cause significant lag on the server. I suspect this is because we're checking items or actions too frequently, which might be overwhelming the system. The TPS was heavily impacted, dropping considerably during testing.

If helpful, I can send over a Spark profile to provide more detailed insights into the performance bottlenecks.

## Rules Used
Here are the two rules we were using during testing:

### Rule 1: Log and Notify on TNT Placement
```plaintext
match "TNT"
name tnt-placement-notify
then notify protect.alert.admins &8[&4TNT Placement Alert&8] &cPlayer: {player} placed TNT at {world} {x}, {y}, {z}. Playtime: {playtime}.
then log &c{player} placed TNT at {world} {x}, {y}, {z} with playtime {playtime}.
then discord tnt_alert &8[&4TNT Placement&8] &cPlayer: {player} placed TNT at {world} {x}, {y}, {z}. Playtime: {playtime}.
```

### Rule 2: Limit TNT Inventory if Playtime < 5 Hours
```plaintext
match "TNT"
name tnt-limit-playtime
require playtime < 5 hours
then confiscate excess
then warn &cYou cannot have more than 1 TNT until you have at least 5 hours of playtime! Current playtime: {playtime}.
then notify protect.alert.admins &8[&4TNT Inventory Alert&8] &cPlayer: {player} had excessive TNT confiscated. Playtime: {playtime}.
then log &c{player} had more than 1 TNT in their inventory. Excess confiscated. Playtime: {playtime}.
```

## Next Steps
Let me know if there's any alternative approach or optimization that might work better. I'm happy to provide the Spark profile if that would help debug the performance impact further.

Thanks again for your support!

**Comment by kangarko** [comment]
Thanks for the detailed report. Unfortunately Protect is not meant for your desired outcome. I highly recommend getting a log block plugin for that, alternatively if you cannot develop a solution in code yourself then you can look into Skript.

Please send me the spark report, and I see if I can improve the performance.
