### ISSUE TITLE
Matched name(s) placeholder

### ISSUE THREAD

**Issue by iiAhmedYT** [kangarko/Protect#3]
1) How it would benefit others?
Would be generally helpful to know which item to expect that was exactly duplicated

2) What would happen if we won't implement this feature? How's your server being affected?
It will be harder to find if these items are hidden somewhere since we use custommodeldata items and a crate key is probably just a STICK so found names if checked for would be really helpful 

3) If suggesting something new - Can the old system be modified/improved instead? Probably

**Comment by kangarko** [comment]
I have added a new filter "rule" to "/protect logs item" so you can use it to match individual rules such as the rule named "crate-key" which should give enough narrowing.
