### ISSUE TITLE
Items are deleted if "delay" or "player delay"is used. 1.8.9

### ISSUE THREAD

**Issue by zylstra1313** [kangarko/Protect#5]
To reproduce

Include this rule in your rules file.

match "DIRT"
name test
player delay 10 seconds
then console say Test

Open a chest with dirt in your inventory.

Open the chest again in under 10 seconds.

(I tested with "then clone" and "then confiscate" at the end as well and got the same results.)
("delay" and "player delay" both seem to function the same way.)

Tested with a freshly generated config with only this rule added.

**Comment by kangarko** [comment]
Thanks, fixed.
