### ISSUE TITLE
Varible to display how many of an item are in the users inventory and the inventory they are looking at combines.

### ISSUE THREAD

**Issue by zylstra1313** [kangarko/Protect#9]
Something like {inventoryitem_amount} that displays how many of the item are seen in the inventory of the user and the inventory they are looking at.
Example: The user has 9 in their inventory and opens a chest with 27 in it. The variable would display 36.

**Comment by kangarko** [comment]
Low priority, dont have time for this now nor soon due to other issues

**Comment by zylstra1313** [comment]
Would you rather I hold off for now on suggestions and bugs for protect?

**Comment by kangarko** [comment]
Yeah for all plugins until ChatControl 11 and Foundation 7 are out please, literally burning out the last month plus I have my real life stuff on top. Thanks.
